[package]
name = "dotdna-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "dotdna_app"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace = true

[dependencies]
dotdna-core = { path = "../crates/dotdna-core" }
dotdna-io = { path = "../crates/dotdna-io" }
serde.workspace = true
tauri.workspace = true
tauri-plugin-dialog.workspace = true

[lints]
workspace = true
